## 1. NUMPY

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3], dtype="int16")

In [3]:
a

array([1, 2, 3], dtype=int16)

In [4]:
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]]) #dtype="int32"

In [6]:
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
b.ndim #get dimension

2

In [8]:
b.shape #get shape

(2, 3)

In [9]:
b.dtype #get type

dtype('float64')

In [10]:
a.dtype

dtype('int16')

In [11]:
a.itemsize #get item size

2

In [12]:
a.size #get while size of a perticular array

3

In [13]:
b.size

6

In [14]:
b.itemsize

8

In [15]:
a.nbytes

6

In [16]:
b.nbytes

48

In [17]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13, 14]])

In [18]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
a[1, 5]

13

In [20]:
a[0, 0]

1

In [21]:
a[1, 5] == a[1, -2]

True

In [22]:
a[1, -2]

13

In [23]:
a[0, :] #get a specific row

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [25]:
a[:, 0]

array([1, 8])

In [26]:
a[:, 1]

array([2, 9])

In [27]:
a[0, 1:-1:2] #[startingindex : endindex: stepsize]

array([2, 4, 6])

In [28]:
a[1, 5] = 20

In [29]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [30]:
a[:, 2] = [1, 1]

In [31]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  1, 11, 12, 20, 14]])

In [32]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [33]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
b[1, 1, 1] #starting index is 0

8

In [36]:
b[:, 1, 0]

array([3, 7])

In [37]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [38]:
b[:, 1, :] = [[0, 0], [0, 0]]

In [39]:
b

array([[[1, 2],
        [0, 0]],

       [[5, 6],
        [0, 0]]])

In [40]:
np.zeros([3, 2, 3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.ones([4, 2, 2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [43]:
np.full((3, 4, 2), 7) #fill with one particular number

array([[[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7]]])

In [44]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  1, 11, 12, 20, 14]])

In [45]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
np.full_like(a.shape, 4)

array([4, 4])

In [47]:
np.random.randint(a)

array([[0, 1, 0, 0, 3, 4, 1],
       [0, 3, 0, 6, 4, 0, 3]])

In [48]:
np.random.randint(3, 4)

3

In [49]:
np.random.rand(3, 4)

array([[0.21413418, 0.22656966, 0.45832979, 0.74164561],
       [0.71766391, 0.66692235, 0.53568628, 0.49112977],
       [0.40510146, 0.31013374, 0.64026089, 0.38540381]])

In [52]:
np.random.randint(7)


6

In [53]:
np.random.randint(7, size=(3, 3))

array([[2, 4, 2],
       [2, 6, 6],
       [3, 0, 3]])

In [54]:
np.random.randint(4, 7, size=(3, 2, 2))

array([[[4, 4],
        [6, 4]],

       [[6, 6],
        [5, 5]],

       [[6, 5],
        [5, 5]]])

In [60]:
np.identity(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
array = np.array([[1, 2, 3]])
r = np.repeat(array, 3, axis=0)
r                                  #repeat on matrix

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [66]:
array = np.array([[1, 2, 3]])
r = np.repeat(array, 3, axis=1)
r

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [67]:
out = np.ones((5, 5))

In [68]:
out

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
z = np.zeros((3, 3))

In [70]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
z[1, 1] = 9

In [72]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [74]:
out[1:4, 1:4] = z

In [79]:
out

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
print(out)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful while copying arrays

In [81]:
a = np.array([1, 2, 3])

In [82]:
a

array([1, 2, 3])

In [83]:
b = a
b[0] = 100

In [84]:
a

array([100,   2,   3])

In [85]:
a = np.array([1, 2, 3])

In [86]:
a

array([1, 2, 3])

In [87]:
b = a.copy()

In [88]:
b[0] = 100

In [89]:
b

array([100,   2,   3])

In [90]:
a

array([1, 2, 3])

### Operations on matrix

In [95]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [96]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
a+2

array([[3, 4, 5],
       [6, 7, 8]])

In [98]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [99]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [100]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [101]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [102]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [103]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

### Linear Algebra

In [104]:
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [105]:
b = np.full((3, 2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [109]:
np.matmul(a, b) #a*b

array([[6., 6.],
       [6., 6.]])

In [111]:
c = np.identity(3)

In [112]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
np.linalg.det(c) #to find determinant

1.0

In [116]:
#determinant
#trace
#singular vector decomposition
#eigenvalues
#matrix norm
#inverse
#etc . . . . . 

### statistics 

In [117]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [118]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
np.min(arr) #axis=0/1

1

In [123]:
np.max(arr)

6

In [124]:
np.sum(arr)

21

In [125]:
np.sum(arr, axis=0)

array([5, 7, 9])

In [126]:
np.sum(arr, axis=1)

array([ 6, 15])

### Recoganizing Arrays

In [127]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [128]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [129]:
after = before.reshape((8, 1))

In [130]:
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [131]:
before.reshape((2, 2, 2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [132]:
before.reshape((1, 8))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [133]:
#vertically stacking vectors

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [134]:
np.vstack([v1, v2, v2])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [135]:
h1 = np.ones((2, 4))

In [136]:
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [137]:
h2 = np.zeros((2, 2))

In [138]:
h2

array([[0., 0.],
       [0., 0.]])

In [139]:
np.hstack((h1, h2, h1))

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

### Masking

In [140]:
a = np.array([10, 12, 15, 16, 20, 8, 11, 7, 17, 19])

In [141]:
a

array([10, 12, 15, 16, 20,  8, 11,  7, 17, 19])

In [142]:
a > 10

array([False,  True,  True,  True,  True, False,  True, False,  True,
        True])

In [146]:
a[a>10]

array([12, 15, 16, 20, 11, 17, 19])